services:
  - type: web
    name: clic-sistemas-catalog
    env: static
    buildCommand: npm install && npm run build
    startCommand: npx http-server . -p $PORT
    envVars:
      - key: NODE_ENV
        value: production
    staticPublishPath: .
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Content-Security-Policy
        value: "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; img-src 'self' data: https: http:; connect-src 'self' https: http:; font-src 'self' https://cdnjs.cloudflare.com;"
